# Hyperparameters
n_timesteps : 5000
n_agents_max : 100
n_agents_initial : 50


# Logging
do_wandb : False
wandb_config:
  project : EcoJAX
do_tb : True
do_cli : True
do_tqdm : True
do_snakeviz : False
do_render : True
config_dirs_to_log :
  run : True
  last_of_all : True
  last_of_agents : True
  last_of_day : False


# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - env : gridworld
  - agents : ne
  - model : mlp
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 



# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .