# Hyperparameters
n_timesteps : 5000
n_agents_max : 5000
n_agents_initial : 1000


# Logging
do_wandb : False
wandb_config:
  project : EcoJAX
do_tb : True
do_cli : False
do_csv : False
do_tqdm : True
do_snakeviz : False
do_render : True
do_global_log : False



# Video recording
do_video : True
n_steps_between_videos : 10000
n_steps_per_video : 1000
n_steps_between_frames : 1
dir_video : logs/videos



# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - env : gridworld
  - agents : ne
  - model : mlp
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 



# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .