# Hyperparameters
seed: 
n_timesteps : 1000
n_agents_max : 5000
n_agents_initial : 200


# Logging
do_wandb : False
wandb_config:
  project : EcoJAX
do_tb : True
do_cli : False
do_csv : True
do_tqdm : True
do_snakeviz : True
do_render : True
do_global_log : True



# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - env : grid_uniform
  - agents : ne
  - model : mlp
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 



# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .