name : Gridworld

# The dimensions of the gridworld
height : 400
width : 400

# Whether the env is terminal, i.e. the simulation stops when all agents are dead
is_terminal : True

# The period of the logging in number of timesteps
# period_logging : ${eval:'${n_timesteps} // 200'}
period_logging : 200


# ======================== Metrics ========================
measures:
  environmental:
    - n_agents
    - n_plants
  immediate:
    - do_action_eat
    # - do_action_reproduce
    - do_action_forward
    - do_action_left
    - do_action_right
    - do_action_backward
    - amount_food_eaten
    - amount_children
    - died
  state:
    - energy
    - age
    - x
    - y
    # - density_agents_observed
    # - density_plants_observed
  behavior: []

aggregators_lifespan:
  - class_string : ecojax.metrics.aggregators:AggregatorLifespanCumulative
    config:
      keys_measures : ${env.measures.immediate}
      n_agents : ${n_agents_max}
      prefix_metric : life_cum
      log_final : true
  - class_string : ecojax.metrics.aggregators:AggregatorLifespanAverage
    config:
      keys_measures : ${merge:${env.measures.immediate}, ${env.measures.state}, ${env.measures.behavior}}
      n_agents : ${n_agents_max}
      prefix_metric : life_avg
  - class_string : ecojax.metrics.aggregators:AggregatorLifespanIncrementalChange
    config:
      keys_measures : ${merge:${env.measures.state}, ${env.measures.behavior}}
      n_agents : ${n_agents_max}
      prefix_metric : inc
  - class_string : ecojax.metrics.aggregators:AggregatorLifespanAbsoluteChange
    config:
      keys_measures : ${merge:${env.measures.state}, ${env.measures.behavior}}
      n_agents : ${n_agents_max}
      prefix_metric : life_var
  - class_string : ecojax.metrics.aggregators:AggregatorLifespanFinal
    config:
      keys_measures : ${merge:${env.measures.state}, ${env.measures.behavior}}
      n_agents : ${n_agents_max}
      prefix_metric : last_final

aggregators_population:
  - class_string : ecojax.metrics.aggregators:AggregatorPopulationMean
    config:
      keys_measures : ${merge:${env.measures.immediate}, ${env.measures.state}, ${env.measures.behavior}}
      keys_measures_prefix : [life, last_final]
      n_agents : ${n_agents_max}
      prefix_metric : pop_mean
  - class_string : ecojax.metrics.aggregators:AggregatorPopulationMovingMean
    config:
      keys_measures : ${merge:${env.measures.behavior}, ${env.measures.state}}
      keys_measures_prefix : []
      n_agents : ${n_agents_max}
      prefix_metric : pop_moving_mean
      learning_rate : 0.05
  - class_string : ecojax.metrics.aggregators:AggregatorPopulationStd
    config:
      keys_measures : ${merge:${env.measures.behavior}, ${env.measures.state}}
      keys_measures_prefix : [life, last_final]
      n_agents : ${n_agents_max}
      prefix_metric : pop_std



# ======================== Video parameters ========================

# The parameters for the video recording
do_video : True
n_steps_between_videos : 1000
n_steps_per_video : 1000
n_steps_between_frames : 1
fps_video : 20
dir_video : logs/videos
height_max_video : 500
width_max_video : 500
dict_name_channel_to_color_tag:
  "sun" : "yellow"
  "plants" : "green"
  "agents" : "blue"
color_background : "gray"



# ======================== Sun Parameters ========================
# The duration of 1 cycle of the sun (for methods using a period)
period_sun : 300

# The method to determine the sun's position, among :
# - "none" : there is no sun
# - "fixed" : the sun does not move at, all and is fixed in the middle latitude
# - "random" : the sun moves randomly
# - "brownian" : the sun moves in a brownian motion
# - "sine" : the sun moves in a sine wave between south and north
# - "linear" : the sun moves in a linear way and wraps around the gridworld when reaching the south
method_sun : "none"

# The radius of the effect of the sun, i.e. the distance at which the sun increase food's growth
radius_sun_effect : 10

# The radius of the perception of the sun by the agents
radius_sun_perception : 40



# ======================== Food Dynamics ========================

# The initial proportion of food tiles at the beginning of the simulation
proportion_plant_initial : 0.2

# The rule for a tile to be a food-tile is the following :
# P(food spawn) = sigmoid(
# + logit(p_base_grow_food) * 1_if_tile_is_not_food
# + factor_sun_grow_food * 1_if_sun_is_up
# + factor_food_grow_food * average_food_in_radius_food_grow_food
# - factor_food_kill_food * average_food_in_radius_food_kill_food
# - logit(p_base_die_food) * 1_if_tile_is_food

# The base probability of a non-food tile to grow spontaneously
p_base_plant_growth : 0.0005
# The base probability of a food tile to die spontaneously
p_base_plant_death : 0.0

# The factor of the sun's effect on the growth of food
factor_sun_effect : 0

# The factor of the effect of the presence of food on the growth of food
factor_plant_reproduction : 2
# The radius of the effect of the presence of food on the growth of food
radius_plant_reproduction : 10

# The factor of the effect of the presence of food on the death of food
factor_plant_asphyxia : 5
# The radius of the effect of the presence of food on the death of food
radius_plant_asphyxia : 15



# ======================== Agent Parameters ========================

# The vision range of an agent. If of value v, the agent will receive the information v tiles around it, so a (2v+1)*(2v+1) grid
vision_range_agent : 5

# The maximum age of an agent
age_max : 500

# The initial energy of an agent
energy_initial : 50
# The energy amount obtained by eating a food tile
energy_food : 10
# The energy threshold under which an agent dies
energy_thr_death : 0
# Whether the agent has to activate the eating action to eat
do_active_eating: true

# The energy required to be able to reproduce
energy_req_reprod : 80
# The energy cost of reproduction
energy_cost_reprod : 20
# Whether the agent has to activate the reproduction action to reproduce.
# In asexual reproduction, the agent will reproduce as soon as the "reproduce" mode is activated.
# In sexual reproduction, agents will reproduce if they are in the same tile and both have the "reproduce" mode activated. To indicate that they are ready to reproduce, they emit reproductive pheromones.
do_active_reprod : false

