name : Gridworld

# The dimensions of the gridworld
height : 200
width : 400

# The type of border of the gridworld, among :
# - "torus" : the gridworld is a torus
# - "wall" : the gridworld has walls
# - "wall_kill" : the gridworld has walls that kill agents
type_border : "wall"



# ======================== Video parameters ========================

# The parameters for the video recording
do_video : True
n_steps_between_videos : 500
n_steps_per_video : 500
n_steps_between_frames : 1
fps_video : 20
dir_videos : logs
height_max_video : 500
width_max_video : 500
dict_name_channel_to_color_tag:
  "sun" : "yellow"
  "plants" : "green"
  "agents" : "blue"
color_background : "gray"



# ======================== Sun Parameters ========================
# The duration of 1 cycle of the sun (for methods using a period)
period_sun : 300

# The method to determine the sun's position, among :
# - "none" : there is no sun
# - "fixed" : the sun does not move at, all and is fixed in the middle latitude
# - "random" : the sun moves randomly
# - "brownian" : the sun moves in a brownian motion
# - "sine" : the sun moves in a sine wave between south and north
# - "linear" : the sun moves in a linear way and wraps around the gridworld when reaching the south
method_sun : "linear"

# The radius of the effect of the sun, i.e. the distance at which the sun increase food's growth
radius_sun_effect : 10

# The radius of the perception of the sun by the agents
radius_sun_perception : 40



# ======================== Food Dynamics ========================

# The initial proportion of food tiles at the beginning of the simulation
proportion_plant_initial : 0.01

# The rule for a tile to be a food-tile is the following :
# P(food spawn) = sigmoid(
# + logit(p_base_grow_food) * 1_if_tile_is_not_food
# + factor_sun_grow_food * 1_if_sun_is_up
# + factor_food_grow_food * average_food_in_radius_food_grow_food
# - factor_food_kill_food * average_food_in_radius_food_kill_food
# - logit(p_base_die_food) * 1_if_tile_is_food

# The base probability of a non-food tile to grow spontaneously
p_base_plant_growth : 0.001
# The base probability of a food tile to die spontaneously
p_base_plant_death : 0.005

# The factor of the sun's effect on the growth of food
factor_sun_effect : 5

# The factor of the effect of the presence of food on the growth of food
factor_plant_reproduction : 4
# The radius of the effect of the presence of food on the growth of food
radius_plant_reproduction : 10

# The factor of the effect of the presence of food on the death of food
factor_plant_asphyxia : 12
# The radius of the effect of the presence of food on the death of food
radius_plant_asphyxia : 20



# ======================== Agent Parameters ========================

# The vision range of an agent. If of value v, the agent will receive the information v tiles around it, so a (2v+1)*(2v+1) grid
vision_range_agent : 10

# The initial energy of an agent
energy_initial : 50
# The energy amount obtained by eating a food tile
energy_food : 10
# The energy threshold under which an agent dies
energy_thr_death : 0

# The energy required to be able to reproduce
energy_req_reprod : 80
# The energy cost of reproduction
energy_cost_reprod : 20
# Whether the agent has to activate the reproduction action to reproduce.
# In asexual reproduction, the agent will reproduce as soon as the "reproduce" mode is activated.
# In sexual reproduction, agents will reproduce if they are in the same tile and both have the "reproduce" mode activated. To indicate that they are ready to reproduce, they emit reproductive pheromones.
do_active_reprod : false

